drop database if exists Prueba_Restaurante;
create database Prueba_Restaurante;
use Prueba_Restaurante;

create table MESAS(
	ID INT(19) AUTO_INCREMENT,
    CAPACIDAD INT(19),
    PRIMARY KEY(ID)
);



create table RESERVACIONES(
	ID INT(19) AUTO_INCREMENT,
    PERSONA VARCHAR(50),
    DUI_PERSONA VARCHAR(12),
    FECHA_RESERVACION DATETIME,
    FECHA_RESERVA VARCHAR(12),
    HORA_RESERVA VARCHAR(12),
    NUM_PERSONAS INT(19),
    ACTIVA BOOLEAN,
    PRIMARY KEY(ID)
);
create table RESERVACIONES_MESAS(
	ID INT(19) AUTO_INCREMENT,
    RESERVACION_ID INT(19),
    MESA_ID INT(19),
    PRIMARY KEY(ID),
    FOREIGN KEY (RESERVACION_ID) REFERENCES RESERVACIONES (ID),
    FOREIGN KEY (MESA_ID) REFERENCES MESAS (ID)
);

INSERT INTO MESAS (CAPACIDAD) VALUES (5);
INSERT INTO MESAS (CAPACIDAD) VALUES (2);
INSERT INTO MESAS (CAPACIDAD) VALUES (2);
INSERT INTO MESAS (CAPACIDAD) VALUES (2);
INSERT INTO MESAS (CAPACIDAD) VALUES (2);
INSERT INTO MESAS (CAPACIDAD) VALUES (5);
INSERT INTO MESAS (CAPACIDAD) VALUES (6);
INSERT INTO MESAS (CAPACIDAD) VALUES (6);
INSERT INTO MESAS (CAPACIDAD) VALUES (6);
INSERT INTO MESAS (CAPACIDAD) VALUES (6);
INSERT INTO MESAS (CAPACIDAD) VALUES (5);
INSERT INTO MESAS (CAPACIDAD) VALUES (2);
INSERT INTO MESAS (CAPACIDAD) VALUES (2);
INSERT INTO MESAS (CAPACIDAD) VALUES (2);
INSERT INTO MESAS (CAPACIDAD) VALUES (2);
INSERT INTO MESAS (CAPACIDAD) VALUES (5);

INSERT INTO RESERVACIONES (PERSONA, DUI_PERSONA, FECHA_RESERVACION, FECHA_RESERVA, HORA_RESERVA, NUM_PERSONAS,ACTIVA) VALUES ('Juan Perez', '1234567890', '2024-02-24 10:00:00', '2024-02-25', '9:00 PM', 4,true);
INSERT INTO RESERVACIONES (PERSONA, DUI_PERSONA, FECHA_RESERVACION, FECHA_RESERVA, HORA_RESERVA, NUM_PERSONAS,ACTIVA) VALUES ('Maria Lopez', '0987654321', '2024-02-23 15:30:00', '2024-02-26', '7:00 PM', 6,true);

insert into RESERVACIONES_MESAS (RESERVACION_ID,MESA_ID) values (1,1);
insert into RESERVACIONES_MESAS (RESERVACION_ID,MESA_ID) values (1,2);
insert into RESERVACIONES_MESAS (RESERVACION_ID,MESA_ID) values (1,3);
insert into RESERVACIONES_MESAS (RESERVACION_ID,MESA_ID) values (2,2);
insert into RESERVACIONES_MESAS (RESERVACION_ID,MESA_ID) values (2,4);
insert into RESERVACIONES_MESAS (RESERVACION_ID,MESA_ID) values (1,2);

select * from MESAS;
select * from RESERVACIONES;
select * from RESERVACIONES_MESAS;




